graph TD
  B4[4] --> B7[7]
  B7 --> B10[10]
  B10 --> B13[13]
  B13 --> B4
  T16[16] --> T19[19]
  T19 --> T22[22]
  T22 --> T25[25]
  T25 --> T16
  B4 <--> T16
  B7 <--> T19
  B10 <--> T22
  B13 <--> T25
  T16 -.collapse.-> B7
  T19 -.collapse.-> B10
  T22 -.collapse.-> B4
  T25 -.collapse.-> B7
